# Generated by Django 5.2.8 on 2025-12-01 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('surname', models.CharField(blank=True, max_length=50, null=True)),
                ('role', models.CharField(choices=[('driver', 'Driver'), ('mechanic', 'Mechanic')], default='driver', max_length=20)),
                ('status', models.CharField(choices=[('registration', 'Registration'), ('pending_vehicle', 'Pending vehicle approval'), ('active', 'Active')], default='registration', max_length=30)),
                ('language', models.CharField(default='ru', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
