# Generated by Django 5.2.8 on 2025-12-04 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('surname', models.CharField(blank=True, max_length=50, null=True)),
                ('role', models.CharField(choices=[('driver', 'Driver'), ('mechanic', 'Mechanic')], default='driver', max_length=20)),
                ('status', models.CharField(choices=[('registration', 'Registration'), ('pending_vehicle', 'Pending vehicle approval'), ('active', 'Active')], default='registration', max_length=30)),
                ('language', models.CharField(default='ru', max_length=5)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('passport_id', models.CharField(blank=True, max_length=20, null=True)),
                ('iin', models.CharField(blank=True, max_length=14, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('passport_front', models.CharField(blank=True, max_length=200, null=True)),
                ('passport_back', models.CharField(blank=True, max_length=200, null=True)),
                ('driver_license', models.CharField(blank=True, max_length=200, null=True)),
                ('selfie', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
