# Generated by Django 5.2.8 on 2025-12-07 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Geozone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('zonetype', models.IntegerField()),
                ('color', models.CharField(blank=True, max_length=16, null=True)),
                ('geometry', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veh_id', models.IntegerField(unique=True)),
                ('imei', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('type', models.CharField(blank=True, max_length=64, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('fuel', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.BigIntegerField()),
                ('start_ts', models.BigIntegerField()),
                ('end_ts', models.BigIntegerField()),
                ('raw_track', models.TextField()),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='TrackPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.BigIntegerField()),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('speed', models.FloatField(blank=True, null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-ts'],
                'indexes': [models.Index(fields=['vehicle', 'ts'], name='vehicles_tr_vehicle_23282a_idx')],
            },
        ),
        migrations.CreateModel(
            name='FuelLevelHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.BigIntegerField()),
                ('fuel', models.FloatField()),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-ts'],
                'indexes': [models.Index(fields=['vehicle', 'ts'], name='vehicles_fu_vehicle_49ddc2_idx')],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.BigIntegerField()),
                ('event_type', models.CharField(max_length=64)),
                ('value', models.CharField(blank=True, max_length=256, null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-ts'],
                'indexes': [models.Index(fields=['vehicle', 'ts'], name='vehicles_ev_vehicle_7b93c4_idx')],
            },
        ),
        migrations.CreateModel(
            name='VehicleStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.BigIntegerField()),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('speed', models.FloatField(blank=True, null=True)),
                ('ignition', models.BooleanField(default=False)),
                ('fuel', models.FloatField(blank=True, null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-ts'],
                'indexes': [models.Index(fields=['vehicle', 'ts'], name='vehicles_ve_vehicle_83c4f6_idx')],
            },
        ),
    ]
