# Generated by Django 5.2.8 on 2025-12-05 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Geozone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('zonetype', models.IntegerField()),
                ('color', models.CharField(blank=True, max_length=16, null=True)),
                ('geometry', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veh_id', models.IntegerField(unique=True)),
                ('imei', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('type', models.CharField(blank=True, max_length=64, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('fuel', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.BigIntegerField()),
                ('start_ts', models.BigIntegerField()),
                ('end_ts', models.BigIntegerField()),
                ('raw_track', models.TextField()),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle')),
            ],
        ),
    ]
