# Generated by Django 5.2.8 on 2025-12-05 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.BigIntegerField()),
                ('event_type', models.CharField(max_length=64)),
                ('value', models.CharField(blank=True, max_length=256, null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-ts'],
                'indexes': [models.Index(fields=['vehicle', 'ts'], name='vehicles_ev_vehicle_7b93c4_idx')],
            },
        ),
        migrations.CreateModel(
            name='FuelLevelHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.BigIntegerField()),
                ('fuel', models.FloatField()),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-ts'],
                'indexes': [models.Index(fields=['vehicle', 'ts'], name='vehicles_fu_vehicle_49ddc2_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrackPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.BigIntegerField()),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('speed', models.FloatField(blank=True, null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-ts'],
                'indexes': [models.Index(fields=['vehicle', 'ts'], name='vehicles_tr_vehicle_23282a_idx')],
            },
        ),
        migrations.CreateModel(
            name='VehicleStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.BigIntegerField()),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('speed', models.FloatField(blank=True, null=True)),
                ('ignition', models.BooleanField(default=False)),
                ('fuel', models.FloatField(blank=True, null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-ts'],
                'indexes': [models.Index(fields=['vehicle', 'ts'], name='vehicles_ve_vehicle_83c4f6_idx')],
            },
        ),
    ]
