# Generated by Django 5.2.8 on 2025-12-11 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='vehiclestatushistory',
            index=models.Index(fields=['ignition'], name='vehicles_ve_ignitio_52f2b8_idx'),
        ),
    ]
